### ISSUE TITLE
Events sync doesn't work

### ISSUE THREAD

**Issue by abbeyn0rma1** [danvratil/FBEventSync#2]
Birthday sync works great. Events don't come over at all.

**Comment by danvratil** [comment]
There's currently an issue with the Facebook API due to the app hitting a rate request limit. Please check again in 24 hours, when we should be again back below the rate.

I'm also pushing a new version out to reduce the number of requests so that this hopefully does not repeat in the future.

Sorry for the inconvenience and let me know if you still run into the problem in few days.

**Comment by danvratil** [comment]
This was fixed in version 13 (update 0.11) which was rolled out to Play Store couple days ago.
